name: Shorts Generator

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Video konusu"
        required: true
        default: "Yapay zeka"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Konuyu Goster
        run: echo ${{ github.event.inputs.topic }}
